import { ExampleCard } from 'src/components/ExampleCard/ExampleCard';
import { ExampleGrid } from 'src/components/ExampleGrid/ExampleGrid';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Next TypeScript Starter</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Next TypeScript Starter</h1>

				<ExampleGrid>
					<ExampleCard to="https://nextjs.org/docs" title="Documentation">
						<p>Find in-depth information about Next.js features and API.</p>
					</ExampleCard>

					<ExampleCard to="https://nextjs.org/learn" title="Learn">
						<p>Learn about Next.js in an interactive course with quizzes!</p>
					</ExampleCard>

					<ExampleCard to="https://github.com/vercel/next.js/tree/canary/examples" title="Examples">
						<p>Discover and deploy boilerplate example Next.js projects.</p>
					</ExampleCard>

					<ExampleCard to="https://vercel.com/new" title="Deploy">
						<p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
					</ExampleCard>
				</ExampleGrid>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}

